name: strong_pass
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
   sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  uuid: ^3.0.7
  get_storage: ^2.1.1
  get: ^4.6.5
  logger: ^1.4.0
  animations: ^2.0.7
  crypto: ^3.0.2
  encrypt: ^5.0.1
  flutter_dotenv: ^5.1.0
  animate_do: ^3.0.2
  secure_application: ^3.8.0
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.6.3
  firebase_crashlytics: ^3.3.3
  random_password_generator: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter_icons:
  android: true
  ios: false
  image_path: lib/resources/icons/launch-icon.png

flutter:

  uses-material-design: true

  assets:
    - lib/resources/images/
    - lib/resources/icons/
    - .env.development
    - .env.production

  fonts:
    - family: Lexend Deca
      fonts:
        - asset: lib/resources/fonts/Lexend_Deca/LexendDeca-Regular.ttf
        - asset: lib/resources/fonts/Lexend_Deca/LexendDeca-Bold.ttf
        - asset: lib/resources/fonts/Lexend_Deca/LexendDeca-SemiBold.ttf
        - asset: lib/resources/fonts/Lexend_Deca/LexendDeca-Medium.ttf
        - asset: lib/resources/fonts/Lexend_Deca/LexendDeca-ExtraBold.ttf
        - asset: lib/resources/fonts/Lexend_Deca/LexendDeca-VariableFont_wght.ttf
        
  
